set(_CATKIN_CURRENT_PACKAGE "erp42_driver")
set(erp42_driver_VERSION "0.0.0")
set(erp42_driver_MAINTAINER "djjin <djjin@todo.todo>")
set(erp42_driver_PACKAGE_FORMAT "2")
set(erp42_driver_BUILD_DEPENDS "roscpp" "std_msgs" "erp42_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "tf")
set(erp42_driver_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "erp42_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "tf")
set(erp42_driver_BUILDTOOL_DEPENDS "catkin")
set(erp42_driver_BUILDTOOL_EXPORT_DEPENDS )
set(erp42_driver_EXEC_DEPENDS "roscpp" "std_msgs" "erp42_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "tf")
set(erp42_driver_RUN_DEPENDS "roscpp" "std_msgs" "erp42_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "tf")
set(erp42_driver_TEST_DEPENDS )
set(erp42_driver_DOC_DEPENDS )
set(erp42_driver_URL_WEBSITE "")
set(erp42_driver_URL_BUGTRACKER "")
set(erp42_driver_URL_REPOSITORY "")
set(erp42_driver_DEPRECATED "")